In [2]:
#Linear Regression 
import numpy as np
from sklearn.linear_model import LinearRegression
X = np.array([[1,1],[1,2],[2,2],[2,3]])
y = np.dot(X, np.array([1,2])) + 3
regr = LinearRegression(fit_intercept=True, normalize = True, copy_X=True, n_jobs=2).fit(X,y)
print(regr.predict(np.array([[3,5]])))
print(regr.score(X,y))
print(regr.coef_)
print(regr.intercept_)

[16.]
1.0
[1. 2.]
3.0000000000000018


In [5]:
#Logistic Regression
from sklearn import datasets
from sklearn import linear_model
from sklearn.datasets import load_iris
X, y = load_iris(return_X_y=True)
LRG = linear_model.LogisticRegression(random_state=0,solver='liblinear',multi_class='auto').fit(X, y)
LRG.score(X, y)

0.96

In [21]:
#Ridge Regression
from sklearn.linear_model import Ridge
import numpy as np
n_samples, n_features = 15, 10
rng = np.random.RandomState(0)
y = rng.randn(n_samples)
X = rng.randn(n_samples, n_features)
rdg = Ridge(alpha=0.5)
rdg.fit(X, y)
rdg.score(X,y)

0.7629498741931635

In [15]:
 rdg.coef_

array([ 0.32720254, -0.34503436, -0.2913278 ,  0.2693125 , -0.22832508,
       -0.8635094 , -0.17079403, -0.36288055, -0.17241081, -0.43136046])

In [16]:
rdg.intercept_

0.5274865723969376

In [10]:
#Bayesian Ridge Regression
from sklearn import linear_model
X = [[0, 0], [1, 1], [2, 2], [3, 3]]
Y = [0, 1, 2, 3]
BayReg = linear_model.BayesianRidge()
print(BayReg.fit(X, Y))

BayesianRidge()


In [11]:
BayReg.predict([[1,1]])

array([1.00000007])

In [12]:
BayReg.coef_

array([0.49999993, 0.49999993])

In [22]:
#LASSO (Least Absolute Shrinkage and Selection Operator)
from sklearn import linear_model
Lreg = linear_model.Lasso(alpha=0.5)
Lreg.fit([[0,0], [1, 1], [2, 2]], [0, 1, 2])


Lasso(alpha=0.5)

In [23]:
Lreg.predict([[0,1]])

array([0.75])

In [24]:
Lreg.coef_

array([0.25, 0.  ])

In [25]:
Lreg.coef_

array([0.25, 0.  ])

In [26]:
Lreg.n_iter_

2

In [27]:
#Multi-task LASSO
from sklearn import linear_model
MTLReg = linear_model.MultiTaskLasso(alpha=0.5)
MTLReg.fit([[0,0], [1, 1], [2, 2]], [[0, 0],[1,1],[2,2]])

MultiTaskLasso(alpha=0.5)

In [28]:
MTLReg.predict([[0,1]])

array([[0.53033009, 0.53033009]])

In [29]:
MTLReg.coef_

array([[4.69669914e-01, 1.76635402e-16],
       [4.69669914e-01, 1.76635402e-16]])

In [30]:
MTLReg.intercept_

array([0.53033009, 0.53033009])

In [31]:
MTLReg.n_iter_

2

In [32]:
# Elastic-Net
from sklearn import linear_model
ENreg = linear_model.ElasticNet(alpha=0.5,random_state=0)
ENreg.fit([[0,0], [1, 1], [2, 2]], [0, 1, 2])

ElasticNet(alpha=0.5, random_state=0)

In [35]:
ENreg.predict([[0,1]])

array([0.73681643])

In [36]:
ENreg.coef_

array([0.26318357, 0.26313923])

In [37]:
ENreg.intercept_

0.47367720941913904

In [38]:
ENreg.n_iter_

15

In [39]:
from sklearn import linear_model
ENreg = linear_model.ElasticNet(alpha=1,random_state=0)
ENreg.fit([[0,0], [1, 1], [2, 2]], [0, 1, 2])

ElasticNet(alpha=1, random_state=0)

In [40]:
#Predicting new values
ENreg.predict([[1,0]])

array([0.90909216])

In [41]:
#weight vectors
ENreg.coef_

array([0.09091128, 0.09090784])

In [42]:
#Calculating intercept
ENreg.intercept_

0.818180878658411

In [43]:
#Calculating number of iterations
ENreg.n_iter_

10

In [44]:
#MultiTaskElasticNet
from sklearn import linear_model
MTENReg = linear_model.MultiTaskElasticNet(alpha=0.5)
MTENReg.fit([[0,0], [1, 1], [2, 2]], [[0, 0],[1,1],[2,2]])


MultiTaskElasticNet(alpha=0.5)

In [45]:
#Predicting new values
MTENReg.predict([[1,0]])

array([[0.69061776, 0.69061776]])

In [46]:
#weight vectors
MTENReg.coef_

array([[0.30943437, 0.30938224],
       [0.30943437, 0.30938224]])

In [47]:
#Calculating intercept
MTENReg.intercept_

array([0.38118338, 0.38118338])

In [48]:
#Calculating number of iterations
MTENReg.n_iter_

15