In [6]:
import numpy as np
from sklearn import linear_model
X = np.array([[-1, -1], [-2, -1], [1, 1], [2, 1]])
Y = np.array([1, 1, 2, 2])
SGDClf = linear_model.SGDClassifier(max_iter=1000, tol=1e3,penalty="elasticnet")
SGDClf.fit(X, Y)

SGDClassifier(penalty='elasticnet', tol=1000.0)

In [7]:
SGDClf.predict([[2.,2.]])

array([2])

In [15]:
SGDClf.coef_

array([[19.61364377,  9.80505936]])

In [10]:
SGDClf.intercept_

array([-10.])

In [12]:
SGDClf.decision_function([[2., 2.]])

array([48.83740627])

In [20]:
#SGD Regressor
import numpy as np
from sklearn import linear_model
n_samples, n_features = 10, 5
rng = np.random.RandomState(0)
y = rng.randn(n_samples)
X = rng.randn(n_samples, n_features)
SGDReg =linear_model.SGDRegressor(max_iter=1000,penalty="elasticnet",loss='huber',tol=1e-3, average=True)
SGDReg.fit(X, y)

SGDRegressor(average=True, loss='huber', penalty='elasticnet')

In [22]:
SGDReg.coef_

array([-0.00377346,  0.00462297, -0.00409135,  0.0065453 ,  0.00359926])

In [24]:
SGDReg.intercept_

array([0.00606018])

In [25]:
SGDReg.t_

61.0