In [1]:
## Support Vector Machines (SVMs)
import numpy as np
X = np.array([[-1, -1], [-2, -1], [1, 1], [2, 1]])
y = np.array([1, 1, 2, 2])
from sklearn.svm import SVC
SVCClf = SVC(kernel='linear',gamma='scale', shrinking=False,)
SVCClf.fit(X, y)

SVC(kernel='linear', shrinking=False)

In [2]:
SVCClf.coef_

array([[0.5, 0.5]])

In [4]:
SVCClf.predict([[-0.5,-0.8]])

array([1])

In [5]:
SVCClf.n_support_

array([1, 1])

In [6]:
SVCClf.support_vectors_

array([[-1., -1.],
       [ 1.,  1.]])

In [7]:
SVCClf.support_

array([0, 2])

In [9]:
SVCClf.intercept_

array([-0.])

In [10]:
SVCClf.fit_status_

0

In [14]:
#NuSVC - NuSVC is Nu Support Vector Classification
import numpy as np
X = np.array([[-1, -1], [-2, -1], [1, 1], [2, 1]])
y = np.array([1, 1, 2, 2])
from sklearn.svm import NuSVC
NuSVCClf = NuSVC(kernel='linear',gamma='scale', shrinking=False,)
NuSVCClf.fit(X, y)

NuSVC(kernel='linear', shrinking=False)

In [15]:
#LinearSVC
from sklearn.svm import LinearSVC
from sklearn.datasets import make_classification
X, y = make_classification(n_features=4, random_state=0)
LSVCClf = LinearSVC(dual = False, random_state=0, penalty='l1',tol=1e-5)
LSVCClf.fit(X, y)

LinearSVC(dual=False, penalty='l1', random_state=0, tol=1e-05)

In [16]:
LSVCClf.predict([[0,0,0,0]])

array([1])

In [17]:
LSVCClf.coef_

array([[0.        , 0.        , 0.91214599, 0.22630641]])

In [18]:
LSVCClf.intercept_

array([0.26860191])

In [20]:
#Regression with SVM
from sklearn import svm
X = [[1, 1], [2, 2]]
y = [1, 2]
SVRReg = svm.SVR(kernel= 'linear', gamma='auto')
SVRReg.fit(X, y)

SVR(gamma='auto', kernel='linear')

In [21]:
SVRReg.coef_

array([[0.4, 0.4]])

In [22]:
SVRReg.predict([[1,1]])

array([1.1])

In [28]:
#NuSVR
from sklearn.svm import NuSVR
import numpy as np
n_samples, n_features = 20, 15
np.random.seed(0)
y = np.random.randn(n_samples)
X = np.random.randn(n_samples, n_features)
NuSVRReg = NuSVR(kernel='linear', gamma='auto',C=1.0, nu=0.1)
NuSVRReg.fit(X, y)

NuSVR(gamma='auto', kernel='linear', nu=0.1)

In [29]:
NuSVRReg.coef_

array([[-0.14904483,  0.04596145,  0.22605216, -0.08125403,  0.06564533,
         0.01104285,  0.04068767,  0.2918337 , -0.13473211,  0.36006765,
        -0.2185713 , -0.31836476, -0.03048429,  0.16102126, -0.29317051]])

In [33]:
#LinearSVR
from sklearn.svm import LinearSVR
from sklearn.datasets import make_regression
X, y = make_regression(n_features=4, random_state=0)
LSVRReg = LinearSVR(dual = False, random_state=0,
loss='squared_epsilon_insensitive',tol=1e-5)
LSVRReg.fit(X, y)

LinearSVR(dual=False, loss='squared_epsilon_insensitive', random_state=0,
          tol=1e-05)

In [37]:
LSVRReg.predict([[0,0,0,0]])

array([-0.01041416])

In [39]:
LSVRReg.coef_

array([20.47354746, 34.08619401, 67.23189022, 87.47017787])

In [41]:
LSVRReg.intercept_

array([-0.01041416])